server:
  port: 8085

spring:
  security:
    oauth2:
      client:
        registration:
          keycloak:
            provider: keycloak
            client-id: front-client
            client-secret: ${FRONT_CLIENT_SECRET:front-secret}
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: openid,profile,accounts.read,accounts.write,cash.write,transfer.write
        provider:
          keycloak:
            authorization-uri: ${keycloak.issuer-uri-external}/protocol/openid-connect/auth
            token-uri: ${keycloak.issuer-uri-internal}/protocol/openid-connect/token
            jwk-set-uri: ${keycloak.issuer-uri-internal}/protocol/openid-connect/certs
            user-info-uri: ${keycloak.issuer-uri-internal}/protocol/openid-connect/userinfo
            user-name-attribute: preferred_username

services:
  gateway:
    url: ${GATEWAY_URL:http://localhost:8080}
