spring:
  application:
    name: accounts-service

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/accounts}
    username: ${SPRING_DATASOURCE_USERNAME:accounts}
    password: ${SPRING_DATASOURCE_PASSWORD:accounts}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yml

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${OAUTH2_ISSUER_URI:http://localhost:8081/realms/my-bank}
          jwk-set-uri: ${OAUTH2_JWK_SET_URI:http://localhost:8081/realms/my-bank/protocol/openid-connect/certs}
      client:
        registration:
          keycloak:
            client-id: ${OAUTH2_CLIENT_ID:accounts-client}
            client-secret: ${OAUTH2_CLIENT_SECRET:accounts-secret}
            authorization-grant-type: client_credentials
            scope: notifications.write
            provider: keycloak
        provider:
          keycloak:
            issuer-uri: ${OAUTH2_ISSUER_URI:http://localhost:8081/realms/my-bank}

server:
  port: ${SERVER_PORT:8080}

bank:
  services:
    notifications:
      url: ${BANK_SERVICES_NOTIFICATIONS_URL:http://localhost:8084}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
      show-details: when-authorized
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true

logging:
  level:
    ru.yandex.practicum.accounts: ${LOGGING_LEVEL_APP:INFO}